name: "Fast_API CICD File"


on: 
  push:
    branches:
        - main

env:
    AWS_REGION: 

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build docker image
              run: docker build ../api --file Dockerfile --tag backend_api:$(date +%s)
